spring:
  application.name: api-demo
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    open-in-view: false
    defer-datasource-initialization: true